-- 6. Create Jobs (10 per recruiter)

-- Recruiter: John Smith (recruiter_john_tech)
INSERT INTO main_app_job (title, description, salary_min, salary_max, location, job_type, is_active, posted_at, posted_by_id, deadline, company_id) VALUES
('Senior Python Developer', 'We are looking for a senior Python developer with 5+ years of experience', 100000.00, 130000.00, 'New York, NY', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '30 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Django Backend Engineer', 'Build scalable web applications using Django framework', 90000.00, 120000.00, 'San Francisco, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '25 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Full Stack Python Developer', 'Full stack development with Python backend and React frontend', 85000.00, 115000.00, 'Boston, MA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '20 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Python REST API Developer', 'Develop RESTful APIs using Python and Django', 80000.00, 110000.00, 'Austin, TX', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '28 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('DevOps Engineer (Python)', 'Manage infrastructure and deployment pipelines', 95000.00, 125000.00, 'Seattle, WA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '35 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Django Developer (Junior)', 'Entry level Django developer position', 60000.00, 80000.00, 'Chicago, IL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '22 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Python Data Engineer', 'Build data pipelines and ETL systems', 100000.00, 130000.00, 'New York, NY', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '30 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Database Administrator (PostgreSQL)', 'Manage PostgreSQL databases and optimize queries', 85000.00, 115000.00, 'Atlanta, GA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '25 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Python Automation Engineer', 'Create automation scripts and tools', 80000.00, 105000.00, 'Denver, CO', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '32 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Python Software Engineer', 'General software engineering role using Python', 85000.00, 120000.00, 'Miami, FL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_john_tech'), CURRENT_DATE + INTERVAL '27 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries'));

-- Recruiter: Sarah Johnson (recruiter_sarah_tech)
INSERT INTO main_app_job (title, description, salary_min, salary_max, location, job_type, is_active, posted_at, posted_by_id, deadline, company_id) VALUES
('Senior Software Architect', 'Design and architect large scale systems', 120000.00, 150000.00, 'San Francisco, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '40 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Technical Lead', 'Lead engineering team and mentor developers', 110000.00, 140000.00, 'New York, NY', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '38 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Solutions Architect', 'Design technical solutions for clients', 100000.00, 135000.00, 'Austin, TX', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '33 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Senior Backend Engineer', 'Build backend systems and microservices', 105000.00, 135000.00, 'Boston, MA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '29 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Staff Engineer', 'Work on complex technical problems', 130000.00, 160000.00, 'Seattle, WA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '45 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Engineering Manager', 'Manage team of engineers', 115000.00, 145000.00, 'Chicago, IL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '35 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Research Engineer', 'Research new technologies and implement proofs of concept', 100000.00, 130000.00, 'San Jose, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '30 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Platform Engineer', 'Build internal developer platforms', 95000.00, 125000.00, 'Portland, OR', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '26 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Systems Engineer', 'Design and maintain system infrastructure', 90000.00, 120000.00, 'Washington, DC', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '24 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries')),
('Security Engineer', 'Implement security best practices and protect systems', 110000.00, 140000.00, 'San Francisco, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_sarah_tech'), CURRENT_DATE + INTERVAL '36 days', (SELECT id FROM main_app_company WHERE name = 'TechCorp Industries'));

-- Recruiter: Mike Wilson (recruiter_mike_cloud)
INSERT INTO main_app_job (title, description, salary_min, salary_max, location, job_type, is_active, posted_at, posted_by_id, deadline, company_id) VALUES
('Cloud Solutions Architect', 'Design cloud solutions on AWS', 115000.00, 145000.00, 'Seattle, WA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '35 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('AWS Solutions Engineer', 'Implement AWS solutions for clients', 100000.00, 130000.00, 'San Francisco, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '30 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Infrastructure Engineer', 'Manage cloud infrastructure', 90000.00, 120000.00, 'Austin, TX', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '28 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('DevOps Engineer', 'Manage CI/CD and deployment pipelines', 85000.00, 115000.00, 'New York, NY', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '25 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Site Reliability Engineer', 'Ensure system reliability and performance', 95000.00, 125000.00, 'Boston, MA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '32 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Security Engineer', 'Implement security in cloud environments', 105000.00, 135000.00, 'Washington, DC', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '37 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Kubernetes Specialist', 'Deploy and manage Kubernetes clusters', 100000.00, 130000.00, 'Portland, OR', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '31 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Infrastructure as Code Engineer', 'Build infrastructure using IaC tools', 90000.00, 120000.00, 'Denver, CO', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '26 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Network Engineer', 'Design and manage cloud networks', 85000.00, 115000.00, 'Miami, FL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '29 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Operations Manager', 'Manage cloud operations and support', 80000.00, 110000.00, 'Phoenix, AZ', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_mike_cloud'), CURRENT_DATE + INTERVAL '23 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions'));

-- Recruiter: Emma Davis (recruiter_emma_cloud)
INSERT INTO main_app_job (title, description, salary_min, salary_max, location, job_type, is_active, posted_at, posted_by_id, deadline, company_id) VALUES
('Senior Cloud Architect', 'Design enterprise cloud solutions', 130000.00, 160000.00, 'San Francisco, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '40 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Migration Specialist', 'Lead cloud migration projects', 110000.00, 140000.00, 'New York, NY', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '36 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Hybrid Cloud Engineer', 'Manage hybrid cloud environments', 100000.00, 130000.00, 'Boston, MA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '33 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Container Orchestration Specialist', 'Manage containerized applications', 95000.00, 125000.00, 'Seattle, WA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '30 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Performance Engineer', 'Optimize cloud performance', 90000.00, 120000.00, 'Austin, TX', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '27 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Database Architect', 'Design cloud databases and storage solutions', 105000.00, 135000.00, 'San Jose, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '34 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Cost Optimizer', 'Optimize cloud costs and billing', 85000.00, 115000.00, 'Chicago, IL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '25 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Disaster Recovery Engineer', 'Build disaster recovery solutions', 100000.00, 130000.00, 'Washington, DC', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '32 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud API Developer', 'Develop cloud APIs and services', 80000.00, 110000.00, 'Portland, OR', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '24 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Integration Engineer', 'Integrate cloud systems with existing infrastructure', 90000.00, 120000.00, 'Atlanta, GA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_emma_cloud'), CURRENT_DATE + INTERVAL '28 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions'));

-- Recruiter: Alex Brown (recruiter_alex_cloud)
INSERT INTO main_app_job (title, description, salary_min, salary_max, location, job_type, is_active, posted_at, posted_by_id, deadline, company_id) VALUES
('Enterprise Cloud Architect', 'Design solutions for enterprise clients', 140000.00, 170000.00, 'San Francisco, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '45 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Principal Cloud Engineer', 'Lead cloud engineering initiatives', 130000.00, 160000.00, 'New York, NY', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '42 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Multi-Cloud Architect', 'Design multi-cloud solutions', 120000.00, 150000.00, 'Seattle, WA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '38 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Platform Engineer', 'Build internal cloud platforms', 100000.00, 130000.00, 'Boston, MA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '35 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Compliance Engineer', 'Ensure cloud compliance and governance', 95000.00, 125000.00, 'Washington, DC', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '31 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Edge Computing Engineer', 'Develop edge computing solutions', 105000.00, 135000.00, 'Austin, TX', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '36 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Serverless Architect', 'Design serverless applications', 100000.00, 130000.00, 'San Jose, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '33 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('API Gateway Specialist', 'Manage API gateways and services', 90000.00, 120000.00, 'Denver, CO', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '29 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Monitoring Engineer', 'Implement monitoring and alerting solutions', 85000.00, 115000.00, 'Chicago, IL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '26 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions')),
('Cloud Automation Engineer', 'Automate cloud operations', 90000.00, 120000.00, 'Miami, FL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_alex_cloud'), CURRENT_DATE + INTERVAL '30 days', (SELECT id FROM main_app_company WHERE name = 'CloudNine Solutions'));

-- Recruiter: David Martinez (recruiter_david_data)
INSERT INTO main_app_job (title, description, salary_min, salary_max, location, job_type, is_active, posted_at, posted_by_id, deadline, company_id) VALUES
('Senior Data Engineer', 'Build data platforms and pipelines', 110000.00, 140000.00, 'San Francisco, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '38 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Data Analyst', 'Analyze data and create insights', 80000.00, 110000.00, 'New York, NY', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '28 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Data Scientist', 'Develop machine learning models', 100000.00, 130000.00, 'Boston, MA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '35 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('ETL Developer', 'Build ETL pipelines and processes', 85000.00, 115000.00, 'Austin, TX', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '32 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Analytics Engineer', 'Build analytics infrastructure', 90000.00, 120000.00, 'Seattle, WA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '30 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Big Data Engineer', 'Work with big data technologies', 105000.00, 135000.00, 'San Jose, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '36 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Data Warehouse Architect', 'Design data warehouse solutions', 110000.00, 140000.00, 'Chicago, IL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '39 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Machine Learning Engineer', 'Build ML pipelines and models', 110000.00, 140000.00, 'Portland, OR', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '37 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Data Quality Engineer', 'Ensure data quality and governance', 85000.00, 115000.00, 'Denver, CO', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '27 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Real-time Data Engineer', 'Build real-time data systems', 105000.00, 135000.00, 'Washington, DC', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_david_data'), CURRENT_DATE + INTERVAL '34 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics'));

-- Recruiter: Lisa Anderson (recruiter_lisa_data)
INSERT INTO main_app_job (title, description, salary_min, salary_max, location, job_type, is_active, posted_at, posted_by_id, deadline, company_id) VALUES
('Principal Data Scientist', 'Lead data science initiatives', 130000.00, 160000.00, 'San Francisco, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '40 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Data Platform Engineer', 'Build data platforms and infrastructure', 110000.00, 140000.00, 'New York, NY', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '38 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Business Analyst', 'Analyze business requirements and data', 75000.00, 105000.00, 'Boston, MA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '25 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Data Visualization Specialist', 'Create data visualizations and dashboards', 80000.00, 110000.00, 'Austin, TX', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '29 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Database Developer', 'Develop and optimize databases', 90000.00, 120000.00, 'Seattle, WA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '31 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Data Integration Specialist', 'Integrate data from multiple sources', 85000.00, 115000.00, 'San Jose, CA', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '28 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('AI/ML Researcher', 'Research AI and ML technologies', 120000.00, 150000.00, 'Chicago, IL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '42 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Data Operations Manager', 'Manage data operations and teams', 105000.00, 135000.00, 'Portland, OR', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '36 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Statistical Analyst', 'Perform statistical analysis on data', 80000.00, 110000.00, 'Denver, CO', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '26 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics')),
('Predictive Analytics Engineer', 'Build predictive models', 100000.00, 130000.00, 'Miami, FL', 'FULL', true, CURRENT_DATE, (SELECT id FROM main_app_user WHERE username = 'recruiter_lisa_data'), CURRENT_DATE + INTERVAL '33 days', (SELECT id FROM main_app_company WHERE name = 'DataStream Analytics'));