# Generated by Django 5.2.12 on 2026-04-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_application_cover_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveApplicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField()),
            ],
        ),
    ]
